<a href="https://colab.research.google.com/github/AzizaSyakira/Pembelajaran-Mesin_Aziza-Syakira_2211533022/blob/main/Pratikum_6_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score

Bagian ini mengimpor pustaka-pustaka yang diperlukan untuk analisis data, termasuk pandas untuk manipulasi data, numpy untuk operasi numerik, dan beberapa modul dari scikit-learn untuk membagi data, membangun model regresi logistik, dan mengevaluasi kinerja model.

In [66]:
# Membaca data dari file CSV dan menampilkannya
df = pd.read_csv('cancer patient data sets.csv')
df.head()

index Patient Id  Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0      0         P1   33       1              2            4             5   
1      1        P10   17       1              3            1             5   
2      2       P100   35       1              4            5             6   
3      3      P1000   37       1              7            7             7   
4      4       P101   46       1              6            8             7   

   OccuPational Hazards  Genetic Risk  chronic Lung Disease  ...  Fatigue  \
0                     4             3                     2  ...        3   
1                     3             4                     2  ...        1   
2                     5             5                     4  ...        8   
3                     7             6                     7  ...        4   
4                     7             7                     6  ...        3   

   Weight Loss  Shortness of Breath  Wheezing  Swallowing Difficulty  \
0            4                    2         2                      3   
1            3                    7         8                      6   
2            7                    9         2                      1   
3            2                    3         1                      4   
4            2                    4         1                      4   

   Clubbing of Finger Nails  Frequent Cold  Dry Cough  Snoring   Level  
0                         1              2          3        4     Low  
1                         2              1          7        2  Medium  
2                         4              6          7        2    High  
3                         5              6          7        5    High  
4                         2              4          2        3    High  

[5 rows x 26 columns]

Bagian ini membaca dataset dari file CSV menggunakan pandas dan menampilkan beberapa baris pertama untuk memberikan gambaran awal tentang data yang dimuat.

In [67]:
df.columns

Index(['index', 'Patient Id', 'Age', 'Gender', 'Air Pollution', 'Alcohol use',
       'Dust Allergy', 'OccuPational Hazards', 'Genetic Risk',
       'chronic Lung Disease', 'Balanced Diet', 'Obesity', 'Smoking',
       'Passive Smoker', 'Chest Pain', 'Coughing of Blood', 'Fatigue',
       'Weight Loss', 'Shortness of Breath', 'Wheezing',
       'Swallowing Difficulty', 'Clubbing of Finger Nails', 'Frequent Cold',
       'Dry Cough', 'Snoring', 'Level'],
      dtype='object')

Bagian ini menampilkan informasi umum tentang dataset,yaitu nama-nama kolom dalam dataset.

In [68]:
df=df[['Age', 'Gender', 'Air Pollution', 'Alcohol use',
       'Dust Allergy', 'OccuPational Hazards', 'Genetic Risk',
       'chronic Lung Disease', 'Balanced Diet', 'Obesity', 'Smoking',
       'Passive Smoker', 'Chest Pain', 'Coughing of Blood', 'Fatigue',
       'Weight Loss', 'Shortness of Breath', 'Wheezing',
       'Swallowing Difficulty', 'Clubbing of Finger Nails', 'Frequent Cold',
       'Dry Cough', 'Snoring', 'Level']]

Bagian ini memilih subset kolom yang relevan dari dataset untuk analisis lebih lanjut dan menampilkan beberapa baris pertama dari data yang sudah dipilih.

In [69]:
df['Level'].value_counts()
df = df.replace({'Level': {'Low': 1, 'Medium': 2, 'High': 3}})
df.head()

Age  Gender  Air Pollution  Alcohol use  Dust Allergy  \
0   33       1              2            4             5   
1   17       1              3            1             5   
2   35       1              4            5             6   
3   37       1              7            7             7   
4   46       1              6            8             7   

   OccuPational Hazards  Genetic Risk  chronic Lung Disease  Balanced Diet  \
0                     4             3                     2              2   
1                     3             4                     2              2   
2                     5             5                     4              6   
3                     7             6                     7              7   
4                     7             7                     6              7   

   Obesity  ...  Fatigue  Weight Loss  Shortness of Breath  Wheezing  \
0        4  ...        3            4                    2         2   
1        2  ...        1            3                    7         8   
2        7  ...        8            7                    9         2   
3        7  ...        4            2                    3         1   
4        7  ...        3            2                    4         1   

   Swallowing Difficulty  Clubbing of Finger Nails  Frequent Cold  Dry Cough  \
0                      3                         1              2          3   
1                      6                         2              1          7   
2                      1                         4              6          7   
3                      4                         5              6          7   
4                      4                         2              4          2   

   Snoring  Level  
0        4      1  
1        2      2  
2        2      3  
3        5      3  
4        3      3  

[5 rows x 24 columns]

Bagian ini mengubah nilai kategorikal pada kolom 'Level' menjadi nilai numerik agar bisa digunakan dalam analisis dan pemodelan.

In [70]:
# Memilih fitur (X) dan target (y) dari dataset
X = df.drop('Level', axis=1)
y = df['Level']

Bagian ini memisahkan fitur (X) yang akan digunakan untuk prediksi dan target (y) yang akan diprediksi dari dataset.

In [71]:
# Membagi dataset menjadi set pelatihan dan pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

Bagian ini membagi dataset menjadi set pelatihan dan pengujian dengan rasio 70:30 menggunakan fungsi train_test_split.

In [72]:
# Membuat model regresi logistik dan melatihnya dengan data pelatihan
Classifier = LogisticRegression(solver='liblinear')
Classifier.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

Bagian ini membuat model regresi logistik dan melatihnya menggunakan data pelatihan.

In [73]:
# Membuat prediksi menggunakan data pengujian
y_test_hat = Classifier.predict(X_test)

# Membuat DataFrame untuk membandingkan nilai aktual dan prediksi
Results = pd.DataFrame({'Actual': y_test, 'Predictions': y_test_hat})
Results.head(10)

Actual  Predictions
507       2            2
818       1            1
452       2            1
368       1            1
242       3            3
929       1            1
262       1            1
810       1            1
318       3            3
49        1            1

Bagian ini membuat prediksi menggunakan data pengujian, kemudian menampilkan hasil prediksi bersama dengan nilai aktual dalam sebuah DataFrame.

In [74]:
# Menghitung akurasi model pada data pelatihan
print(accuracy_score(y_test, y_test_hat))
y_train_hat = Classifier.predict(X_train)
print(accuracy_score(y_train, y_train_hat))

0.9733333333333334
0.98


Bagian ini menghitung akurasi model pada data pengujian dan data pelatihan untuk menilai kinerja model.

In [75]:
# Memeriksa probabilitas prediksi model
y_test_hat_proba = Classifier.predict_proba(X_test)
print(y_test_hat_proba.shape)
y_test_hat_proba[0:5, :]

(300, 3)


array([[1.30064968e-01, 8.69935031e-01, 1.61592280e-09],
       [9.74931348e-01, 2.29356116e-02, 2.13304087e-03],
       [9.34586553e-01, 3.33970114e-02, 3.20164351e-02],
       [9.78288107e-01, 1.06361531e-04, 2.16055319e-02],
       [2.30254447e-02, 5.87972220e-04, 9.76386583e-01]])

Bagian ini memeriksa probabilitas prediksi dari model dan menampilkan beberapa baris pertama dari DataFrame yang membandingkan nilai aktual, prediksi, dan probabilitas prediksi.

In [76]:
# Membuat DataFrame untuk membandingkan nilai aktual, prediksi, dan probabilitas prediksi
pls = y_test_hat_proba[:, 1]
Results = pd.DataFrame({'Actual': y_test, 'Predictions': y_test_hat, 'Prob(Class = 3)': pls})
Results.head(5)

Actual  Predictions  Prob(Class = 3)
507       2            2         0.869935
818       1            1         0.022936
452       2            1         0.033397
368       1            1         0.000106
242       3            3         0.000588

Bagian ini membuat DataFrame 'result' untuk membandingkan nilai aktual, prediksi, dan probabilitas kelas 3.

In [77]:
# Fungsi untuk menampilkan metrik evaluasi model
def perform(y_pred):
    print("Precision : ", precision_score(y_test, y_test_hat, average='micro'))
    print("Recall : ", recall_score(y_test, y_test_hat, average='micro'))
    print("Accuracy : ", accuracy_score(y_test, y_test_hat))
    print("F1 Score : ", f1_score(y_test, y_test_hat, average='micro'))
    cm = confusion_matrix(y_test, y_pred)
    print("\n", cm)
    print("\n")
    print("**" * 27 + "\n" + " " * 16 + "Classification Report\n" + "**" * 27)
    print(classification_report(y_test, y_test_hat))
    print("**" * 27 + "\n")

perform(y_test_hat)

Precision :  0.9733333333333334
Recall :  0.9733333333333334
Accuracy :  0.9733333333333334
F1 Score :  0.9733333333333334

 [[ 89   0   0]
 [  5  88   3]
 [  0   0 115]]


******************************************************
                Classification Report
******************************************************
              precision    recall  f1-score   support

           1       0.95      1.00      0.97        89
           2       1.00      0.92      0.96        96
           3       0.97      1.00      0.99       115

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300

******************************************************



Bagian ini mendefinisikan fungsi perform yang menghitung dan menampilkan metrik evaluasi model seperti precision, recall, accuracy, F1 score, serta classification report untuk memberikan rincian lebih lanjut tentang kinerja model pada setiap kelas.